<?php

namespace ContainerRuEXM3B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0tVoPgdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0tVoPgd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0tVoPgd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DealController::index' => ['privates', '.service_locator.v6EQnOu', 'get_ServiceLocator_V6EQnOuService', true],
            'App\\Controller\\FormController::addDeal' => ['privates', '.service_locator.0U6.opQ', 'get_ServiceLocator_0U6_OpQService', true],
            'App\\Controller\\FormController::addUser' => ['privates', '.service_locator.l_Toyz2', 'get_ServiceLocator_LToyz2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DealController:index' => ['privates', '.service_locator.v6EQnOu', 'get_ServiceLocator_V6EQnOuService', true],
            'App\\Controller\\FormController:addDeal' => ['privates', '.service_locator.0U6.opQ', 'get_ServiceLocator_0U6_OpQService', true],
            'App\\Controller\\FormController:addUser' => ['privates', '.service_locator.l_Toyz2', 'get_ServiceLocator_LToyz2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DealController::index' => '?',
            'App\\Controller\\FormController::addDeal' => '?',
            'App\\Controller\\FormController::addUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DealController:index' => '?',
            'App\\Controller\\FormController:addDeal' => '?',
            'App\\Controller\\FormController:addUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
