<?php

namespace ContainerRuEXM3B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0U6_OpQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0U6.opQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0U6.opQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cateRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'cateRepo' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
