<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRuEXM3B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRuEXM3B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRuEXM3B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRuEXM3B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRuEXM3B\App_KernelDevDebugContainer([
    'container.build_hash' => 'RuEXM3B',
    'container.build_id' => '04ea3650',
    'container.build_time' => 1611562175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRuEXM3B');
